name       : pptp
version    : 1.9.0
release    : 2
source     :
    - https://pilotfiber.dl.sourceforge.net/project/pptpclient/pptp/pptp-1.9.0/pptp-1.9.0.tar.gz : 0b1e8cbfc578d3f5ab12ee87c5c2c60419abfe9cc445690a8a19c320b11c9201
license    : GPL-2.0
component  : network.clients
summary    : pptp is an implementation of the PPTP protocol for Linux and other Unix systems
description: |
    pptp is an implementation of the PPTP protocol for Linux and other Unix systems
build      : |
    %make
install    : |
    %make_install
